# Generated by Django 4.1.13 on 2025-04-30 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategori Seminar',
                'verbose_name_plural': 'Kategori Seminar',
            },
        ),
        migrations.CreateModel(
            name='Pembicara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profesi', models.CharField(blank=True, max_length=100)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Pembicara',
                'verbose_name_plural': 'Pembicara',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tanggal', models.DateField(verbose_name='Tanggal Seminar')),
                ('waktu_mulai', models.TimeField(verbose_name='Waktu Mulai')),
                ('waktu_selesai', models.TimeField(verbose_name='Waktu Selesai')),
                ('lokasi', models.CharField(max_length=255)),
                ('deskripsi', wagtail.fields.RichTextField(blank=True)),
                ('kuota_peserta', models.PositiveIntegerField(default=100)),
                ('harga_tiket', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gambar_utama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminar', to='seminar.kategoriseminar')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SeminarIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SeminarPembicara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('topik_presentasi', models.CharField(blank=True, max_length=255)),
                ('pembicara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_pembicara', to='seminar.pembicara')),
                ('seminar', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembicara_seminar', to='seminar.seminar')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PendaftaranPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=20)),
                ('institusi', models.CharField(blank=True, max_length=100)),
                ('tanggal_daftar', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_pembayaran', models.BooleanField(default=False)),
                ('kode_pendaftaran', models.CharField(max_length=20, unique=True)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran', to='seminar.seminar')),
            ],
            options={
                'verbose_name': 'Pendaftaran Peserta',
                'verbose_name_plural': 'Pendaftaran Peserta',
            },
        ),
    ]
